# -*- coding: utf-8 -*-
"""SentinelX.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A9vjyXUPV-tiIUtHEI3STDZplcKIhYVZ
"""

# Install required packages (run once)
#!pip install -q earthengine-api geemap folium geopandas rasterio matplotlib

import ee

# Authenticate (will give link to log in once)
ee.Authenticate()

# Initialize with your project
ee.Initialize(project='intricate-pad-471317-q8')   # <-- replace with your Project ID

print("✅ Earth Engine initialized with project")

import folium

# Coordinates of the land
lat, lon = 22.941793, 81.076843

# Create a folium map centered at the location
m = folium.Map(location=[lat, lon], zoom_start=14)

# Popup information (Certificate + claimant details)
popup_info = f"""
<b>Certificate No.:</b> FRA-MP-2025-DIND001<br>
<b>Issue Date:</b> 11-09-2025<br><br>

<b>Name of Claimant(s):</b> Bhima Gond<br>
<b>Spouse:</b> Lalita Gond<br>
<b>Father/Mother:</b> Late Kali Gond<br><br>

<b>Address:</b> Village Samnapur, Dindori District, Madhya Pradesh<br>
<b>Village:</b> Samnapur<br>
<b>Gram Panchayat:</b> Samnapur GP<br>
<b>Tehsil/Taluka:</b> Dindori<br>
<b>District:</b> Dindori<br><br>

<b>Land Details:</b><br>
Survey/Plot No.: 45A/12B<br>
Area: 2.3 hectares<br>
Type: Agricultural (upland, rice + millets)<br><br>

<b>Boundaries:</b><br>
North: Forest Buffer Zone<br>
South: Kharmer River bank<br>
East: Neighbor’s farmland (Sahu family)<br>
West: Village road
"""

# Add marker with popup
folium.Marker(
    location=[lat, lon],
    popup=folium.Popup(popup_info, max_width=400),
    tooltip="FRA Patta Holder: Bhima Gond",
    icon=folium.Icon(color="green", icon="leaf", prefix="fa")
).add_to(m)

# Show map
m

import folium
from shapely.geometry import Polygon

# Coordinates of the land center point
lat, lon = 22.941793, 81.076843

# Approx square polygon (151m per side, 2.3 hectares)
# Rough calculation: ~0.00136 degrees ≈ 151m (at this latitude)
offset = 0.00136 / 2

polygon_coords = [
    [lat - offset, lon - offset],
    [lat - offset, lon + offset],
    [lat + offset, lon + offset],
    [lat + offset, lon - offset],
    [lat - offset, lon - offset]  # close loop
]

# Create base map
m = folium.Map(location=[lat, lon], zoom_start=15)

# Popup info for FRA certificate
popup_info = f"""
<b>Certificate No.:</b> FRA-MP-2025-DIND001<br>
<b>Issue Date:</b> 11-09-2025<br><br>
<b>Claimant:</b> Bhima Gond<br>
<b>Spouse:</b> Lalita Gond<br>
<b>Father/Mother:</b> Late Kali Gond<br><br>
<b>Survey/Plot No.:</b> 45A/12B<br>
<b>Area:</b> 2.3 hectares<br>
<b>Type:</b> Agricultural (upland, rice + millets)<br>
"""

# Add marker
folium.Marker(
    location=[lat, lon],
    popup=folium.Popup(popup_info, max_width=400),
    tooltip="FRA Patta Holder: Bhima Gond",
    icon=folium.Icon(color="green", icon="leaf", prefix="fa")
).add_to(m)

# Add polygon (dummy 2.3 ha)
folium.Polygon(
    locations=polygon_coords,
    color="blue",
    fill=True,
    fill_opacity=0.3,
    tooltip="Approx. Land Parcel (2.3 ha)"
).add_to(m)

# ---------------------------
# Add Sentinel-2 satellite imagery layer (latest composite)
# ---------------------------
import ee
import geemap

# Get Sentinel-2 surface reflectance image
sentinel = (ee.ImageCollection('COPERNICUS/S2_SR')
            .filterBounds(ee.Geometry.Point(lon, lat))
            .filterDate('2025-01-01', '2025-09-01')  # adjust date range
            .sort('CLOUDY_PIXEL_PERCENTAGE')
            .first()
            .visualize(bands=['B4', 'B3', 'B2'], min=0, max=3000))

# Convert EE layer to folium
map_id_dict = ee.Image(sentinel).getMapId()
folium.raster_layers.TileLayer(
    tiles=map_id_dict['tile_fetcher'].url_format,
    attr='Google Earth Engine - Sentinel-2',
    overlay=True,
    name='Sentinel-2 True Color',
    opacity=0.7
).add_to(m)

# Add layer control
folium.LayerControl().add_to(m)

# Display map
m

import folium
import ee

# Center point
lat, lon = 22.941793, 81.076843

# Initialize folium map
m = folium.Map(location=[lat, lon], zoom_start=15)

# Add FRA marker
popup_info = """
<b>Certificate No.:</b> FRA-MP-2025-DIND001<br>
<b>Issue Date:</b> 11-09-2025<br><br>
<b>Claimant:</b> Bhima Gond<br>
<b>Spouse:</b> Lalita Gond<br>
<b>Father/Mother:</b> Late Kali Gond<br><br>
<b>Survey/Plot No.:</b> 45A/12B<br>
<b>Area:</b> 2.3 hectares<br>
<b>Type:</b> Agricultural (upland, rice + millets)<br>
"""

folium.Marker(
    [lat, lon],
    popup=folium.Popup(popup_info, max_width=400),
    tooltip="FRA Patta Holder: Bhima Gond",
    icon=folium.Icon(color="green", icon="leaf", prefix="fa")
).add_to(m)

# Draw dummy polygon (~2.3 ha square)
offset = 0.00136 / 2  # ≈ 151m
polygon_coords = [
    [lat - offset, lon - offset],
    [lat - offset, lon + offset],
    [lat + offset, lon + offset],
    [lat + offset, lon - offset],
    [lat - offset, lon - offset]
]

folium.Polygon(
    polygon_coords,
    color="blue",
    fill=True,
    fill_opacity=0.3,
    tooltip="Approx. Land Parcel (2.3 ha)"
).add_to(m)

# --- Sentinel-2 true color ---
sentinel = (ee.ImageCollection('COPERNICUS/S2_SR')
            .filterBounds(ee.Geometry.Point(lon, lat))
            .filterDate('2025-01-01', '2025-09-01')
            .sort('CLOUDY_PIXEL_PERCENTAGE')
            .first()
            .visualize(bands=['B4', 'B3', 'B2'], min=0, max=3000))

map_id_dict = ee.Image(sentinel).getMapId()
folium.raster_layers.TileLayer(
    tiles=map_id_dict['tile_fetcher'].url_format,
    attr='Google Earth Engine - Sentinel-2',
    overlay=True,
    name='Sentinel-2 True Color',
    opacity=0.7
).add_to(m)

# Layer control
folium.LayerControl().add_to(m)

m

import folium
import ee

# Coordinates
lat, lon = 22.941793, 81.076843

# Base Map
m = folium.Map(location=[lat, lon], zoom_start=15)

# FRA Marker
popup_info = """
<b>Certificate No.:</b> FRA-MP-2025-DIND001<br>
<b>Issue Date:</b> 11-09-2025<br><br>
<b>Claimant:</b> Bhima Gond<br>
<b>Spouse:</b> Lalita Gond<br>
<b>Father/Mother:</b> Late Kali Gond<br><br>
<b>Survey/Plot No.:</b> 45A/12B<br>
<b>Area:</b> 2.3 hectares<br>
<b>Type:</b> Agricultural (upland, rice + millets)<br>
"""

folium.Marker(
    [lat, lon],
    popup=folium.Popup(popup_info, max_width=400),
    tooltip="FRA Patta Holder: Bhima Gond",
    icon=folium.Icon(color="green", icon="leaf", prefix="fa")
).add_to(m)

# Polygon (dummy 2.3 ha square)
offset = 0.00136 / 2  # ≈151m
polygon_coords = [
    [lat - offset, lon - offset],
    [lat - offset, lon + offset],
    [lat + offset, lon + offset],
    [lat + offset, lon - offset],
    [lat - offset, lon - offset]
]

folium.Polygon(
    polygon_coords,
    color="blue",
    fill=True,
    fill_opacity=0.3,
    tooltip="Approx. Land Parcel (2.3 ha)"
).add_to(m)

# -------------------
# Sentinel-2 imagery
# -------------------
point = ee.Geometry.Point(lon, lat)
s2 = (ee.ImageCollection('COPERNICUS/S2_SR')
      .filterBounds(point)
      .filterDate('2025-01-01', '2025-09-01')
      .sort('CLOUDY_PIXEL_PERCENTAGE')
      .first())

# Layers
true_color = s2.visualize(bands=['B4','B3','B2'], min=0, max=3000)
false_color = s2.visualize(bands=['B8','B4','B3'], min=0, max=3000)
ndvi = s2.normalizedDifference(['B8','B4']).visualize(min=0, max=1, palette=['white','yellow','green'])
ndwi = s2.normalizedDifference(['B3','B8']).visualize(min=-1, max=1, palette=['brown','blue'])

# Add each layer with unique names (so they show in LayerControl)
layers = [
    (true_color, "Sentinel-2 True Color"),
    (false_color, "Sentinel-2 False Color"),
    (ndvi, "NDVI (Vegetation)"),
    (ndwi, "NDWI (Water)")
]

for layer, name in layers:
    map_id = ee.Image(layer).getMapId()
    folium.raster_layers.TileLayer(
        tiles=map_id['tile_fetcher'].url_format,
        attr='Google Earth Engine',
        overlay=True,
        name=name,
        opacity=0.7
    ).add_to(m)

# ✅ Layer toggle panel
folium.LayerControl(collapsed=False).add_to(m)

m.save("map.html")